spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/echo_music?useUnicode=true&characterEncoding=utf-8&useSSL=false # ???? MySQL ?????
    username: root #
    password: root
    # type: com.alibaba.druid.pool.DruidDataSource # ?????

  security:
    user:
      name: "root"  # 清空默认用户名（生产环境需结合自定义认证）
      password: "root"  # 清空默认密码

  # Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# JWT 配置
jwt:
  secret: your-secret-key-here  # JWT 密钥
  expire: 86400  # Token 过期时间（秒）

minio:
  endpoint: http://localhost:9000 # 修改你的 MinIO 端点
  accessKey: wNyYymssKFsMrSX3zonj  # 修改你的 MinIO Access Key
  secretKey: qWNi4SufFMkZkKtJZV1sieULCkfeCLQ8nAjxNeWJ # 修改你的 MinIO Secret Key
  bucket: echo-music-data # 确认 Bucket 名称与你创建的一致

  # 头像上传限制
  avatar:
    max-size: 5MB # 最大文件大小
    allowed-types: image/jpeg,image/png # 允许的文件类型